name: Manually Run Tests Pipeline

on: 
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm install

      - name: Run Prettier
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm run lint:prettier

  eslint:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm install

      - name: Run ESLint
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm run lint:js

  stylelint:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm install

      - name: Run StyleLint
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm run lint:style